### ISSUE TITLE
firefox_keywords  is not working anymore!

### ISSUE THREAD

**Issue by wada3n** [kupferlauncher/kupfer#131]
Please provide enough information to reproduce the issue.

### Environment

Kupfer Version:v319
Window Manager: Mutter
Desktop Environment: Gnome 3.36
Linux Distribution: Ubuntu 20.04

by the way the same error in linux mint 19.3
### Actual Behaviour
firefox_keywords  is not working anymore!
### Expected Behaviour
It does not give any results, and  keep showing an error message , the Firefox keywords is empty.
I hope to fix this bug and provide new updates to the best launcher ever.

**Comment by KarolBedkowski** [comment]
I think this was fixed in 14f7a7767c90263732e20b54328e9b49896f75f6

**Comment by wada3n** [comment]
@KarolBedkowski 
thanks for the reply 
i try replace the two files but still not working for me.
what am I doing wrong?

**Comment by KarolBedkowski** [comment]
Hi,
Please close kupfer, clear cache directory (~/.cache/kupfer) and start kupfer.
Also there may be problem with refreshing - firefox not update places / keywords immediate after change (rather on close); Kupfer load this data in 1h intervals.
If this not help please reopen this bug by more details are required - please start kupfer with --debug flag and attach logs.

**Comment by wada3n** [comment]
Hi
Thank you very much
I tried my best but unfortunately it did not work.
I have written some plugins for Google Search and YouTube Search based on the DuckDuckGo search plugin and they are working fine.
I tried to know exactly where the problem was but couldn't.
this is the logs with kupfer --debug

[kupfer_debug.log](https://github.com/kupferlauncher/kupfer/files/4535734/kupfer_debug.log)
My sincere appreciation to you.

**Comment by KarolBedkowski** [comment]
There is no error, so should work. But Kupfer can't find firefox profile - in log should appear lines like:
```
D [kupfer.plugin.firefox] BookmarksSource: Reading bookmarks from file:/home/k/.mozilla/firefox/bog3ybte.k.20171115/places.sqlite?immutable=1&mode=ro
D [kupfer.plugin.firefox] BookmarksSource: Loaded 420 items
...
D [kupfer.plugin.firefox_keywords] KeywordsSource: Reading bookmarks from file:/home/k/.mozilla/firefox/bog3ybte.k.20171115/places.sqlite?immutable=1&mode=ro
D [kupfer.plugin.firefox_keywords] KeywordsSource: Loaded 2 items
```

Please check where your firefox profile is located  - kupfer look for default profile defined in ~/.mozilla/firefox/profile.ini. Maybe this path is in your env is different.

**Comment by wada3n** [comment]
Yes, it's on the same path!
I don't know exactly where the problem is,
Maybe in the deb file version in Ubuntu repository!
I will try to build it myself from here.

**Comment by KarolBedkowski** [comment]
Please check this version 
https://raw.githubusercontent.com/KarolBedkowski/kupfer/bug131-ff/kupfer/plugin/firefox_keywords.py
I've added more logging, so maybe we'll see what's wrong.

**Comment by wada3n** [comment]
hi @KarolBedkowski 
Thank you very much
I tried that but still nothing.

> D [kupfer.core.plugins]: Loading kupfer.plugin.firefox_keywords
D [kupfer.core.plugins]:   from /usr/share/kupfer/kupfer/plugin/firefox_keywords.py
D [kupfer.core.sources]: Add <kupfer.plugin.firefox_keywords.KeywordSearchSource>
D [kupfer.core.sources]: Add <kupfer.plugin.firefox_keywords.SearchWithEngine>
D [kupfer.core.sources] SourcePickler: Loading Firefox Keywords from k5776fc94bb6e77d9abcaa250afd0f0e5-v5.pickle.gz
D [kupfer.core.sources]: Add <kupfer.plugin.firefox_keywords.KeywordsSource>
D [kupfer.core.plugins]: Loading kupfer.plugin.image

**Comment by KarolBedkowski** [comment]
I must wait for end of rescan (message "[kupfer.core.sources] PeriodicRescanner: Campaign finished, pausing 3600 s')
You can also (in debug mode) find "Firefox keywords" and launch in  right panel Rescan action.

**Comment by wada3n** [comment]
@KarolBedkowski I found the problem, bro 
The problem with the path extracted from the profile.ini
the path is : `Default= ****.default-release` not `path=****.default`
the plugin finds the wrong path.
When I statically changed it in the firefox_keywords.py, it works fine.
I don’t know if I have a problem in my machine or are in recent updates from Firefox.
by the way this is the profile.ini  I have;
```
Default=****.default-release
Locked=1

[Profile1]
Name=default
IsRelative=1
Path=****.default
Default=1

[Profile0]
Name=default-release
IsRelative=1
Path=****.default-release

[General]
StartWithLastProfile=1
Version=2
```

**Comment by KarolBedkowski** [comment]
Well, your profiles file work for me. There is no magic. 
Kupfer don't look for Default from first line; it search for section (profile) with Default=1 and Path set, or - when no Default=1 found; for section with Path=....
So as long ***** not hide strange file name - it should work.
I pushed updated file - you may look, maybe this will be work for you. If not, I need all logs...

**Comment by wada3n** [comment]
in my understanding, the default path is (profile) with Default=1  which is the following : `Path=****.default` 

kupfer log this:
`D [found default profile]: ****.default`
`D [using profile]: ****.default`

this not working for me, not showing the `Reading bookmarks` part,  but when i modified that to `Path=****.default-release` ([Profile0])
the plugin worked fine.
`D [kupfer.plugin.firefox_keywords] KeywordsSource: Reading bookmarks from file:/home/ghani/.mozilla/firefox/****.default-release/places.sqlite?immutable=1&mode=ro
`
`D [kupfer.plugin.firefox_keywords] KeywordsSource: Loaded 4 items`

Well, I will try to permanently delete Firefox and use the new file.

**Comment by a11g0rhythm** [comment]
Kupfer build from github
Window Manager: Compiz
Desktop Environment: Mate 1.24
Linux Distribution: Ubuntu 20.04

I have this same problem, I clean ~/.mozilla/firefox/profiles.ini and add Default=1 to my profile.
firefox_keywords and firefox_bookmarks start working

**Comment by KarolBedkowski** [comment]
You may look on this update:
https://github.com/KarolBedkowski/kupfer/tree/bug131-ff
(https://github.com/KarolBedkowski/kupfer/blob/bug131-ff/kupfer/plugin/firefox_keywords.py).

Still - without real, whole profiles.ini - is only guessing whats wrong...

**Comment by wada3n** [comment]
Hi @KarolBedkowski,
Sorry for the delay.
These are all files
I'm using kupfer from Linux Mint
My profiles.ini :
![Sélection_007](https://user-images.githubusercontent.com/13304792/81414495-facd9b80-913e-11ea-92ff-501d98e78e4e.png)

Place SQLITE file:

![Sélection_008](https://user-images.githubusercontent.com/13304792/81414506-fe612280-913e-11ea-80df-e1ff8ca53e57.png)

and the logs:
[kupferdebug.log](https://github.com/kupferlauncher/kupfer/files/4599471/kupferdebug.log)


I think we need this:
```D [kupfer.plugin.firefox_keywords]: found install default profile /home/home/.mozilla/firefox/4mthz7fb.default-release

D [kupfer.plugin.firefox_keywords] KeywordsSource: Loaded items`

D [kupfer.plugin.firefox_keywords]: found install default profile /home/home/.mozilla/firefox/4mthz7fb.default-release`

D [kupfer.plugin.firefox_keywords] KeywordsSource: Reading bookmarks from file:/home/home/.mozilla/firefox/4mthz7fb.default-release/places.sqlite?immutable=1&mode=ro

D [kupfer.plugin.firefox_keywords] KeywordsSource: Reading bookmarks from file:file:/home/home/.mozilla/firefox/4mthz7fb.default-release/places.sqlite%3fimmutable=1&mode=ro?immutable=1&mode=ro
Exception in [kupfer.plugin.firefox_keywords] KeywordsSource:
NoneType: None
D [kupfer.plugin.firefox_keywords]: found install default profile /home/home/.mozilla/firefox/4mthz7fb.default-release
D [kupfer.plugin.firefox_keywords] KeywordsSource: Reading bookmarks from file:/home/home/.mozilla/firefox/4mthz7fb.default-release/places.sqlite?immutable=1&mode=ro
D [kupfer.plugin.firefox_keywords] KeywordsSource: Reading bookmarks from file:file:/home/home/.mozilla/firefox/4mthz7fb.default-release/places.sqlite%3fimmutable=1&mode=ro?immutable=1&mode=ro
Exception in [kupfer.plugin.firefox_keywords] KeywordsSource:
NoneType: None
D [kupfer.plugin.firefox_keywords] KeywordsSource: Loaded 0 items

```
`
What else can I do to help?

**Comment by KarolBedkowski** [comment]
@wada3n Thank you. I notice strange firefox behavior - Firefox user profile from section Install... as a default and not look on profiles with Default=1 (and not update this flag). I'm not sure it's bug or feature. 

Please check last patch:
https://github.com/KarolBedkowski/kupfer/tree/bug131-ff
(https://github.com/KarolBedkowski/kupfer/blob/bug131-ff/kupfer/plugin/firefox_keywords.py).
Now kupfer should select right profile.

**Comment by KarolBedkowski** [comment]
ok.
I found another bug; maybe this solve this problem.
Reading places.sqlite is tricky; please check also with closed firefox.

**Comment by wada3n** [comment]
@KarolBedkowski yes, it strange, 
in ubuntu 20.04 with default kupfer when i set the path statically in the file:
```
def get_firefox_home_file(needed_file):
    firefox_dir = os.path.expanduser("~/.mozilla/firefox")
    if not os.path.exists(firefox_dir):
        return None

    config = RawConfigParser({"Default" : 0})
    config.read(os.path.join(firefox_dir, "profiles.ini"))
    path ="hfm3dg.default-release"

    if path == None:
        return ""

    if path.startswith("/"):
        return os.path.join(path, needed_file)

    return os.path.join(firefox_dir, path, needed_file)

Work well!

**Comment by wada3n** [comment]
No, not working at all

```
D [kupfer.plugin.firefox_keywords]: found install default profile /home/home/.mozilla/firefox/4mthz7fb.default-release
D [kupfer.plugin.firefox_keywords] KeywordsSource: Reading bookmarks from file:/home/home/.mozilla/firefox/4mthz7fb.default-release/places.sqlite?immutable=1&mode=ro
D [kupfer.plugin.firefox_keywords] KeywordsSource: Reading bookmarks error unable to open database file
D [kupfer.plugin.firefox_keywords] KeywordsSource: Reading bookmarks from file:/home/home/.mozilla/firefox/4mthz7fb.default-release/places.sqlite?immutable=1&mode=ro
D [kupfer.plugin.firefox_keywords] KeywordsSource: Reading bookmarks error unable to open database file
D [kupfer.plugin.firefox_keywords] KeywordsSource: Reading bookmarks from file:/home/home/.mozilla/firefox/4mthz7fb.default-release/places.sqlite?immutable=1&mode=ro
D [kupfer.plugin.firefox_keywords] KeywordsSource: Reading bookmarks error unable to open database file
D [kupfer.plugin.firefox_keywords] KeywordsSource: Read bookmarks failed
Exception in [kupfer.plugin.firefox_keywords] KeywordsSource:
NoneType: None
D [kupfer.plugin.firefox_keywords] KeywordsSource: Loaded 0 items
```

**Comment by KarolBedkowski** [comment]
Well, if /home/home/.mozilla/firefox/4mthz7fb.default-release/places.sqlite is correct path and "4mthz7fb.default-release" is right profile (not "hfm3dg.default-release" as mentioned 2 comment above), there is other problem with opening this file.

Probably firefox keep lock on it and Kupfer can't open it. Please try to close all instances of firefox - we'll see whats happen.

**Comment by wada3n** [comment]
No the `hfm3dg.default-release` is from ubuntu 20.04 an other system, and i'm using the old kupfer.
As I told you I changed the path directly in it and it works. I am using it for my laptop!

But in my second PC  with linux mint 19.3  `4mthz7fb` profile ,I tried today as you see, the problem is still the same, even after closing all instances of firefox and restarting the system.
I will try another system in the Virtual Box.
I think there is a problem with Firefox updates.
Thank you very much and I hope to find a solution soon.

**Comment by KarolBedkowski** [comment]
I have no idea what is may be wrong. I can't reproduce this bug.
But, you may tray new version
https://github.com/KarolBedkowski/kupfer/tree/fix-ff
In this version I added configuration for selecting profile (by name or by path) for firefox bookmarks and firefox keywords plugins.

**Comment by wada3n** [comment]
@KarolBedkowski Thank you.
Now it works great, And also the new way to choose a profile is excellent.

**Comment by wada3n** [comment]
@KarolBedkowski Thank you.
Now it works great, And also the new way to choose a profile is excellent.
I wish you all the best; much happiness and success.
